name: ArticStock
description: "A new Flutter project."

# Evita publicación accidental en pub.dev
publish_to: 'none'

# Versionado del proyecto
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  excel: ^2.1.0
  cupertino_icons: ^1.0.8
  open_filex: ^4.3.2
  shared_preferences: ^2.5.3  # (o la última versión)
  fl_chart: ^0.66.0
  window_manager: ^0.3.5
  flutter_launcher_icons: ^0.14.4
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/artic_logo.png
    - assets/logo/logo_sin_titulo.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_sin_titulo.png"
