// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgl07_NIAuvf4FUDeZMFXsjZYDfN-x3Q',
    appId: '1:261389226382:web:6644f77e0d885bc971d4df',
    messagingSenderId: '261389226382',
    projectId: 'artick-stock',
    authDomain: 'artick-stock.firebaseapp.com',
    storageBucket: 'artick-stock.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpj77sN2D-sNxzwkHnM5S_FdQ-3tvemc',
    appId: '1:261389226382:android:2580946ac250135c71d4df',
    messagingSenderId: '261389226382',
    projectId: 'artick-stock',
    storageBucket: 'artick-stock.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTgl07_NIAuvf4FUDeZMFXsjZYDfN-x3Q',
    appId: '1:261389226382:web:432624de7530790271d4df',
    messagingSenderId: '261389226382',
    projectId: 'artick-stock',
    authDomain: 'artick-stock.firebaseapp.com',
    storageBucket: 'artick-stock.firebasestorage.app',
  );
}
